services:
   caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:


networks:
  default:
    external: true
    name: noctis
