networks:
  frontend: # Name of the network
    external: true # Use an existing network

volumes:
  caddy_data:
  caddy_config:

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    volumes:
      - /root/s-caddy/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /root/s-caddy/caddy/site:/srv
      - /root/s-caddy/caddy/caddy_data:/data
      - /root/s-caddy/caddy/caddy_config:/config
    ports:
      - '80:80'
      - '443:443'